CAMERAS:
- id: vid_1
  rtsp: src/video.mp4
- id: vid_2
  rtsp: src/video_2.mp4
COLORS:
  IN: (0,255,255)
  OUT: (128,0,128)
  default: (0,0,255)
FLASK_HOSTNAME: localhost
FLASK_PORT: 5000
LOGGER:
  log_file_path: app.log
  max_kept_size: 102400
  max_log_size: 10485760
NUM_THREADS: 1
REDIS_HOSTNAME: localhost
REDIS_PORT: 6379
STREAM_MAXLEN: 1
demo_height: 720
demo_width: 1280
env_selected: 2
