CAMERAS:
- id: vid_1
  rtsp: src/video.mp4
- id: vid_2
  rtsp: src/video_2.mp4
LOGGER:
  log_file_path: app.log
  max_kept_size: 102400
  max_log_size: 10485760
NUM_THREADS: 1
REDIS_HOSTNAME: localhost
REDIS_PORT: 6379
STREAM_MAXLEN: 1
YOLO_MODEL_PATH: models/yolov8n.pt
env_selected: 2
